// src/components/admin/DeckForm.vue
<template>
  <form @submit.prevent="handleSubmit" class="space-y-6">
    <BaseInput
      v-model="formData.title"
      label="Deck Title"
      placeholder="Enter deck title..."
      required
      :error="errors.title"
    />

    <BaseTextarea
      v-model="formData.description"
      label="Description"
      placeholder="Enter deck description..."
      required
      :rows="4"
      :error="errors.description"
    />

    <div class="flex justify-end space-x-3 pt-4">
      <BaseButton
        type="button"
        variant="secondary"
        @click="$emit('cancel')"
      >
        Cancel
      </BaseButton>
      
      <BaseButton
        type="submit"
        variant="primary"
        :loading="loading"
        :loading-text="isEditing ? 'Updating...' : 'Creating...'"
      >
        {{ isEditing ? 'Update Deck' : 'Create Deck' }}
      </BaseButton>
    </div>
  </form>
</template>

<script setup lang="ts">
import { reactive, watch } from 'vue'
import BaseInput from '@/components/ui/BaseInput.vue'
import BaseTextarea from '@/components/ui/BaseTextarea.vue'
import BaseButton from '@/components/ui/BaseButton.vue'

interface DeckData {
  title: string
  description: string
}

interface Props {
  initialData?: DeckData
  loading?: boolean
  isEditing?: boolean
}

const props = withDefaults(defineProps<Props>(), {
  initialData: () => ({ title: '', description: '' }),
  loading: false,
  isEditing: false,
})

const emit = defineEmits<{
  submit: [data: DeckData]
  cancel: []
}>()

const formData = reactive<DeckData>({
  title: props.initialData.title,
  description: props.initialData.description,
})

const errors = reactive({
  title: '',
  description: '',
})

// Watch for prop changes to update form data
watch(() => props.initialData, (newData) => {
  formData.title = newData.title
  formData.description = newData.description
}, { deep: true })

const validateForm = (): boolean => {
  errors.title = ''
  errors.description = ''

  if (!formData.title.trim()) {
    errors.title = 'Title is required'
  }

  if (!formData.description.trim()) {
    errors.description = 'Description is required'
  }

  return !errors.title && !errors.description
}

const handleSubmit = () => {
  if (validateForm()) {
    emit('submit', { ...formData })
  }
}
</script>

// src/components/admin/DeckForm.tsx
import React, { useState, useEffect } from 'react'
import BaseInput from '@/components/ui/BaseInput'
import BaseTextarea from '@/components/ui/BaseTextarea'
import BaseButton from '@/components/ui/BaseButton'

interface DeckData {
  title: string
  description: string
}

interface DeckFormProps {
  initialData?: DeckData
  loading?: boolean
  isEditing?: boolean
  onSubmit: (data: DeckData) => void
  onCancel: () => void
}

const DeckForm: React.FC<DeckFormProps> = ({
  initialData = { title: '', description: '' },
  loading = false,
  isEditing = false,
  onSubmit,
  onCancel,
}) => {
  const [formData, setFormData] = useState<DeckData>({
    title: initialData.title,
    description: initialData.description,
  })

  const [errors, setErrors] = useState({
    title: '',
    description: '',
  })

  // Update form data when initialData changes
  useEffect(() => {
    setFormData({
      title: initialData.title,
      description: initialData.description,
    })
  }, [initialData])

  const validateForm = (): boolean => {
    const newErrors = {
      title: '',
      description: '',
    }

    if (!formData.title.trim()) {
      newErrors.title = 'Title is required'
    }

    if (!formData.description.trim()) {
      newErrors.description = 'Description is required'
    }

    setErrors(newErrors)
    return !newErrors.title && !newErrors.description
  }

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    if (validateForm()) {
      onSubmit(formData)
    }
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      <BaseInput
        value={formData.title}
        onChange={(e) => setFormData((prev) => ({ ...prev, title: e.target.value }))}
        label="Deck Title"
        placeholder="Enter deck title..."
        required
        error={errors.title}
      />

      <BaseTextarea
        value={formData.description}
        onChange={(e) => setFormData((prev) => ({ ...prev, description: e.target.value }))}
        label="Description"
        placeholder="Enter deck description..."
        required
        rows={4}
        error={errors.description}
      />

      <div className="flex justify-end space-x-3 pt-4">
        <BaseButton type="button" variant="secondary" onClick={onCancel}>
          Cancel
        </BaseButton>

        <BaseButton
          type="submit"
          variant="primary"
          loading={loading}
          loadingText={isEditing ? 'Updating...' : 'Creating...'}
        >
          {isEditing ? 'Update Deck' : 'Create Deck'}
        </BaseButton>
      </div>
    </form>
  )
}

export default DeckForm
